tls:
  stores:
    default:
      defaultCertificate:
        certFile: /certs/basewp.local.pem
        keyFile: /certs/basewp.local-key.pem

  certificates:
    - certFile: /certs/basewp.local.pem
      keyFile: /certs/basewp.local-key.pem